# -*- coding: utf-8 -*-
"""LeandroRetamal_SoledadFaundez_PGY1121_SECCION_JORNADA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YSCAEbMGSobsBQ5Zh-IeJY28FhS39mk-
"""

bandera = True
bandera_2 = True
opc = ''
lista_tipo_vehiculo = []
tipo_vehiculo = ''
lista_patente = []
patente = ''
lista_marca = []
marca = ''
lista_precio = []
precio = ''
opc_multa = ''
fecha_multa = ''
monto_multa = ''
lista_multas = []  # Nueva lista :D
opc_certificado = []
buscar_patente_2 = []
import random
precio_1 = random.randint(1500, 3500)
precio_2 = random.randint(1500, 3500)
precio_3 = random.randint(1500, 3500)
from datetime import datetime
patron_fecha = "%d/%m/%Y"
opc_multa_2 = ''
lista_fecha_registro = []
fecha_registro = ''
lista_nombre_duenio = []
nombre_duenio = ''
buscar_patente = ''
index_patente = ''
nada = 'nada'
suma_multa = 0

while bandera:
  print('''
¡Bienvenido al menú de Auto seguro!
Por favor, seleccione una de las opciones numéricas mostradas a continuación:

1) Grabar
2) Buscar
3) Imprimir certificados
4) Salir
  ''')
  opc = input('Opción: ')
  while not opc.isnumeric() or int(opc) >= 5 or int(opc) <= 0:
    print('Opción inválida, seleccione una opción entre el 1 al 4')
    opc = input('Opción: ')
  if int(opc) == 1:
    tipo_vehiculo = input('Ingrese el tipo del vehículo a grabar: ')
    while not tipo_vehiculo.isalpha():
      print('Tipo de vehiculo inválido')
      tipo_vehiculo = input('Ingrese el tipo del vehículo a grabar: ')
    lista_tipo_vehiculo.append(tipo_vehiculo)
    while True:
      patente = input('Ingrese la patente del vehículo a grabar: ')
      if patente[:4].isalpha() and len(patente) == 6:
        lista_patente.append(patente)
        break
      else:
        print('patente invalida')
    marca = input('Ingrese la marca del vehículo a grabar: ')
    while len(marca) <= 1 or len(marca) >= 16 or marca.isnumeric():
        print('Marca inválida, debe contener un mínimo de 2 caracteres y máximo 15 caracteres')
        marca = input('Ingrese la marca del vehículo a grabar: ')
    lista_marca.append(marca)
    precio = input('Ingrese el precio del vehículo a grabar (mínimo $5.000.000)')
    while not precio.isnumeric() or int(precio) <= 4999999:
        print('Precio inválido')
        precio = input('Ingrese el precio del vehículo a grabar (mínimo $5.000.000): ')
    lista_precio.append(int(precio))
    print('''
¿El vehículo posee multas?
Seleccione una de las opciones numéricas

1) Si
2) No
      ''')
    opc_multa = input('Opción: ')
    while not opc_multa.isnumeric() or int(opc_multa) <= 0 or int(opc_multa) >= 3:
        print('Opción inválida, seleccione una de las opciones numéricas')
        opc_multa = input('Opción: ')
    if int(opc_multa) == 1:
        suma_multa = 0 + 1
        while True:
          fecha_multa = input('Ingrese la fecha de la multa (Ej: dd/mm/aaaa): ')
          try:
            date = datetime.strptime(fecha_multa, patron_fecha)
            break
          except ValueError:
            print('La fecha ingresada no es válida')
        monto_multa = input('Ingrese el monto de la multa: ')
        while not monto_multa.isnumeric():
          print('Monto inválido')
          monto_multa = input('Ingrese el monto de la multa: ')
        lista_multas.append([[fecha_multa, monto_multa]])  # Crea una nueva lista dentro de la lista xd
        while bandera_2:
          print('''
¿Desea agregar más multas al vehículo?
Seleccione una de las opciones numéricas

1) Si
2) No
          ''')
          opc_multa_2 = input('Opción: ')
          while not opc_multa_2.isnumeric() or int(opc_multa_2) >= 3 or int(opc_multa_2) <= 0:
            print('Opción inválida')
            opc_multa_2 = input('Opción: ')
          if int(opc_multa_2) == 1:
            suma_multa = suma_multa + 1
            while True:
              fecha_multa = input('Ingrese la fecha de la multa (Ej: dd/mm/aaaa): ')
              try:
                date = datetime.strptime(fecha_multa, patron_fecha)
                break
              except ValueError:
                print('La fecha ingresada no es válida')
            monto_multa = input('Ingrese el monto de la multa: ')
            while not monto_multa.isnumeric():
              print('Monto inválido')
              monto_multa = input('Ingrese el monto de la multa: ')
            lista_multas[-1].append([fecha_multa, monto_multa])  # ahota lo agrega a la nueva lista
          elif int(opc_multa_2) == 2:
            break
          else:
            print('Opción inválida')
    elif int(opc_multa) == 2:
        lista_multas.append([[nada, nada]])  # lo agrega a una lista pero diciendo que no tiene nadi
    else:
        print('Opción inválida, seleccione una de las opciones numéricas')

    while True:
      fecha_registro = input('Ingrese la fecha de registro del vehículo (Ej: dd/mm/aaaa): ')
      try:
        date = datetime.strptime(fecha_registro, patron_fecha)
        break
      except ValueError:
        print('La fecha ingresada no es válida')

    lista_fecha_registro.append(fecha_registro)
    nombre_duenio = input('Ingrese el nombre del dueño del vehículo: ')
    while not nombre_duenio.isalpha():
       print('Nombre inválido')
       nombre_duenio = input('Ingrese el nombre del dueño del vehículo: ')
    lista_nombre_duenio.append(nombre_duenio)
    print('¡Vehículo grabado exitosamente dentro del sistema!')

  elif int(opc) == 2:
    buscar_patente = input('Ingrese la patente del vehículo que desea buscar: ')
    while not buscar_patente[:4].isalpha() and len(buscar_patente) == 6:
      print('Patente inválida')
      buscar_patente = input('Ingrese la patente del vehículo que desea buscar: ')
    if buscar_patente in lista_patente:
      index_patente = lista_patente.index(buscar_patente)
      suma_multa = int(index_patente) + suma_multa
      print('\nPatente del vehículo:', lista_patente[index_patente], '\nDueño del vehículo:', lista_nombre_duenio[index_patente], '\nMarca del vehículo:', lista_marca[index_patente], '\nTipo de vehículo:', lista_tipo_vehiculo[index_patente], '\nPrecio del vehículo: $', lista_precio[index_patente], '\nFecha de registro del vehículo:', lista_fecha_registro[index_patente])
      while not lista_multas[index_patente][0][0] == 'nada':
        int(suma_multa) -1
        print('\nMultas:')
        for multa in lista_multas[index_patente]:
          fecha_multa, monto_multa = multa
          print('\nFecha de la multa:', fecha_multa)
          print('Monto de la multa:', monto_multa)
        break
    else:
      print('La patente ingresada no se encuentra dentro del sistema')
  elif int(opc) == 3:
    buscar_patente_2 = input('Ingrese la patente del vehículo: ')
    if buscar_patente_2 in lista_patente:
      index_patente_2 = lista_patente.index(buscar_patente_2)
      print(f'''
¿Qué certificado desea imprimir?
Ingrese el número del certificado que desea imprimir

1) Certificado emisión de contaminantes     Precio: ${precio_1}
2) Certificado de anotaciones vigentes      Precio: ${precio_2}
3) Certificado de multas                    Precio: ${precio_3}
    ''')
      opc_certificado = input('Opción: ')
      while not opc_certificado.isnumeric() or int(opc_certificado) >= 4 or int(opc_certificado) <= 0:
        print('Opción inválida')
        opc_certificado = input('Opción: ')
      if int(opc_certificado) == 1:
        print(f'''
Certificado de Emisión de Contaminantes

Nombre del certificado: Emisión de contaminantes
Patente del auto: {lista_patente[index_patente_2]}
Dueño actual: {lista_nombre_duenio[index_patente_2]}
Valor: ${precio_1}
        ''')

      elif int(opc_certificado) == 2:
        print(f'''
Certificado de Anotaciones vigentes

Nombre del certificado: Anotaciones vigentes
Patente del auto: {lista_patente[index_patente_2]}
Dueño actual: {lista_nombre_duenio[index_patente_2]}
Valor: ${precio_2}
        ''')
      elif int(opc_certificado) == 3:
        print(f'''
Certificado de Multas

Nombre del certificado: Multas
Patente del auto: {lista_patente[index_patente_2]}
Dueño actual: {lista_nombre_duenio[index_patente_2]}
Valor: ${precio_3}
        ''')
      else:
        print('Opción inválida')
    else:
      print('La patente no se encuentra en el sistema')
  elif int(opc) == 4:
    print('Saliendo...')
    print('Leandro Retamal y Soledad Faúndez \nVersión 6.9')
    break
  else:
    print('Opción inválida, seleccione una opción entre el 1 al 4')